### ISSUE TITLE
. set-env.sh cannot be executed?

### ISSUE THREAD

**Issue by jiaxyan** [non-equivocation/catena-java#1]
![image](https://user-images.githubusercontent.com/29909655/30674421-8605f7ac-9eac-11e7-9efa-f7361583a6a3.png)
as shown in the image, is this set-env.sh file set to be non-executable?

**Comment by alinush** [comment]
Ooops, I never noticed this issue. So here's a 2-years later reply.
The set-env.sh script is meant to be "sourced" rather than executed, so it can set the proper environment variables in your shell.

In other words, instead of ``./set-env.sh``, which won't do anything and can't be even done because (as you noticed) it doesn't have execute permissions on it, do:
```
source set-env.sh
```
...or equivalently (notice the dot):

```
 . set-env.sh
```
This is explained in the [README.md](https://github.com/non-equivocation/catena-java/blob/master/README.md) of the repo, which I hope you read.
